# Generated by Django 4.1.7 on 2023-03-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csk', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='usercall',
            name='service_points',
            field=models.IntegerField(choices=[(1, 'Электрик'), (2, 'Сантехник'), (3, 'Инженер'), (4, 'Жилые и коммунальные службы'), (5, 'Архитектор/Дизайнер'), (6, 'Юрист'), (7, 'Прочее')], default=7),
        ),
        migrations.AddField(
            model_name='usercall',
            name='status_points',
            field=models.IntegerField(choices=[(1, 'Срочный запрос'), (2, 'Запрос в процессе'), (3, 'Запрос осуществлен'), (4, 'Запрос отклонен')], default=2),
        ),
    ]
